[project]
name = "tdp-tdpbrowser"
version = "0.1.1"
description = "Browse and place touchdesigner packages (TDP)."
readme = "README.md"
keywords=["TouchDesigner", "TouchDesignerPackage"]
requires-python = ">=3.11.10"
dependencies = [
 "tdp-markdownrender",
 "tdp-touchutilcollection>=0.8.0",
]

[[project.authors]]
name = "Wieland Hilker"
email = "Wieland@PlusPlus.One"

[dependency-groups]
dev = [ "monkeybrain>=0.4;sys_platform =='win32'",]


[tool.monkeybrain]
touchdesigner-version = "2025.32460"
enforce-version = "latest-version"
projectfile = "Project.toe"

[tool.touchdesigner.TDPyEnvManagerContext]
contextVersion = 2
createdByVersion = "1.4.1"
active = true
mode = "Python vEnv"
envName = ".venv"
installPath = "."
pythonVersion = "3.11"
autoSetup = false
autoSetupReqs = []
autoSetupSyncReqs = false
extraPaths = ["src"]
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"] # Or any folder where the packeg-structure resides on.

[tool.setuptools.package-data]
"*" = ["*.tox"] # Otherwise binary tox-files will be ignored
